- hosts: localhost
  tasks:
  - name: download java
    local_action: https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.tar.gz /media/pkgs/

  - name: copy java source
    copy:
     src: /media/pkgs/openjdk-12.0.1_linux-x64_bin.tar.gz
     dest: {{ playbook_dir }}/docker/
    delegate_to: localhost

  - name: up docker-compose
    docker_compose:
      project_src: {{ playbook_dir }}/docker/
